### ISSUE TITLE
Contextily background tiles dont work in version>1.1.0

### ISSUE THREAD

**Issue by nailend** [openego/eDisGo#195]
The following deprecated warning comes up plotting grids in the [example notebook](https://github.com/openego/eDisGo/blob/dev/examples/edisgo_simple_example.ipynb). For example cell [7] `edisgo.plot_mv_grid_topology(technologies=True)`

```
WARNING:root:Background map could not be plotted due to the following error: module 'contextily' has no attribute 'sources'
```

This happend using contextily==1.2.0. but not version==1.1.0.

**Comment by khelfen** [comment]
This will be fixed in #241 :)
